import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { setReady, setNotReady, getAgentDetails, getCapabilities, getNotReadyReasonCodes } from './supervisorAdminAPI';

const initialState = {
  success: false,
  capabilities: null,
  agent: null,
  agentState: null,
  reasonCodes: null
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.

export const readyThunk = createAsyncThunk(
  'state/ready',
  async () => {
    await setReady();
    // The value we return becomes the `fulfilled` action payload
    return true;
  }
);

export const notReadyThunk = createAsyncThunk(
  'state/notReady',
  async ({reasonCode}) => {
    await setNotReady(reasonCode);
    // The value we return becomes the `fulfilled` action payload
    return true;
  }
);
export const getReasonCodesThunk = createAsyncThunk(
  'state/reasonCodes',
  async () => {
    return await getNotReadyReasonCodes();
    // The value we return becomes the `fulfilled` action payload
  }
);

export const getCapabilitiesThunk = createAsyncThunk(
  'state/getCapabilities',
  async () => {
    return await getCapabilities();
    // The value we return becomes the `fulfilled` action payload
  }
);

export const getAgentDetailsThunk = createAsyncThunk(
  'state/getAgentDetails',
  async () => {
    return await getAgentDetails();
    // The value we return becomes the `fulfilled` action payload
  }
);

export const stateSlice = createSlice({
  name: 'state',
  initialState,
  reducers: {
    setCurrentAgentState: (state, action) => {
      state.agentState = action.payload;
    },
  },
  // // The `reducers` field lets us define reducers and generate associated actions
  // reducers: {
  //   increment: (state) => {
  //     // Redux Toolkit allows us to write "mutating" logic in reducers. It
  //     // doesn't actually mutate the state because it uses the Immer library,
  //     // which detects changes to a "draft state" and produces a brand new
  //     // immutable state based off those changes
  //     state.value += 1;
  //   },
  //   decrement: (state) => {
  //     state.value -= 1;
  //   },
  //   // Use the PayloadAction type to declare the contents of `action.payload`
  //   incrementByAmount: (state, action) => {
  //     state.value += action.payload;
  //   },
  // },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: {
    [readyThunk.fulfilled]: (state) => {
      return { ...state, success: true }
    },
    [readyThunk.rejected]: (state) => {
      return { ...state, success: false }
    },
    [notReadyThunk.fulfilled]: (state) => {
      return { ...state, success: true }
    },
    [notReadyThunk.rejected]: (state) => {
      return { ...state, success: false }
    },
    [getReasonCodesThunk.fulfilled]: (state, action) => {
      return { ...state, success: true, reasonCodes: action.payload }
    },
    [getReasonCodesThunk.rejected]: (state) => {
      return { ...state, success: false }
    },
    [getCapabilitiesThunk.fulfilled]: (state, action) => {
      return { ...state, success: true, capabilities: action.payload }
    },
    [getCapabilitiesThunk.rejected]: (state) => {
      return { ...state, success: false }
    },
    [getAgentDetailsThunk.fulfilled]: (state, action) => {
      return { ...state, success: true, agent: action.payload }
    },
    [getAgentDetailsThunk.rejected]: (state) => {
      return { ...state, success: false }
    },
  },
});
export const { setCurrentAgentState } = stateSlice.actions;

export default stateSlice.reducer;
